Brush tool enh
HaikuArchives/ArtPaint pull request #168
Opened 2022-05-11 04:46 UTC by dsizzle

Added some enhancments to Brush Tool - angle slider, lock dimensions button, and enabled reset brush button. 

Fixes #167

2022-05-11 05:00 UTC, dsizzle commented
oh I also added "SetEnabled" and "Value" to NumberSliderControl.

2022-05-11 06:15 UTC, humdingerb requested changes
There are two things that that I'm not sure are easy to implement:
1. If you "Lock dimensions", the "Height" silder is disabled and keeps showing the old value, even when you change the "Width" slider. Actually, it should mirror the width value. Only if you deactivate the "Lock", it jumps to the current width value.     
If it's not possible to keep updating a disabled slider, maybe the slider shouldn't be disabled at all, but both sliders could set each others value. So the user could grab any of them and both get updated accordingly.

2. Can a stored brush remember its "Lock" setting?. Currently, if you restore some asymmetrical brush (width != height) while having your "Lock" on, the panel 'lies': It shows the asymmetrical brush with a locked "Height". Impossible. :)     
Also, if you disable the "Lock", the brush snaps to be symmetrical, which probably isn't what you want.

2022-05-11 06:15 UTC, humdingerb commented on artpaint/tools/BrushEditor.cpp
> +#include <stdio.h>
Debug leftover?

2022-05-12 06:43 UTC, dsizzle commented on artpaint/tools/BrushEditor.cpp
> +		new BCheckBox(B_TRANSLATE("Lock Dimensions"),
fixed

2022-05-12 06:43 UTC, dsizzle commented on artpaint/tools/BrushEditor.cpp
> +#include <stdio.h>
fixed!

2022-05-12 06:49 UTC, dsizzle commented
1. I decided to keep the slider enabled, so the user can drag either width or height, but when you click lock it always locks height = width.  Not much can be done there.  I think it feels better this way.
2. it didn't make sense to store the lock setting imo because it's more of a UI convenience than a brush property.  I just made sure to uncheck that box when you select a brush from the brush window. idk if you have stronger feelings about it.  this eliminates the weirdness you described, however.

2022-05-12 16:50 UTC, humdingerb approved these changes

2022-05-12 16:52 UTC, humdingerb commented
Your reasoning for 1) and 2) is sound. Let's merge!

2022-05-12 16:54 UTC, merged

2022-05-12 17:45 UTC, dsizzle commented
Thanks! While trying to resolve the alpha drawing, it's challenging to figure out the math for brush fading. I really wanted to be able to reset the angle to 0 and figured might as well add the other stuff.